repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.7.2
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
    repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.26.0
    hooks:
      - id: gitleaks
  - hooks:
      - id: yamlfmt
    repo: https://github.com/google/yamlfmt
    rev: v0.16.0
  - hooks:
      - args:
          - --markdown-linebreak-ext=md
        id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - exclude: .vscode
        id: check-json
      - id: no-commit-to-branch
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
  - hooks:
      - id: cargo-deny
        args: ["--all-features", "check"]
    repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.18.2
  - repo: https://github.com/crate-ci/typos
    rev: v1.32.0
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.0
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
